name: luoyi_dart_test
description: dart test
version: 2.1.1
repository: https://github.com/luoyi58624/luoyi_dart_test

environment:
  sdk: ^3.3.3

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
